"""fix login and password

Revision ID: 0ea74752f28b
Revises: f262eac11ece
Create Date: 2025-02-18 08:50:36.926113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea74752f28b'
down_revision: Union[str, None] = 'f262eac11ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_user', 'login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('external_user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('external_user', 'login',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
