"""Add theme

Revision ID: 180e281a61e9
Revises: 3a5578b42159
Create Date: 2025-01-17 09:55:44.172172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180e281a61e9'
down_revision: Union[str, None] = '3a5578b42159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentation_files', sa.Column('theme', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presentation_files', 'theme')
    # ### end Alembic commands ###
