"""edit role_model

Revision ID: 2bb21ca0a10e
Revises: 1df688c3e6b1
Create Date: 2025-01-30 11:38:26.180649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb21ca0a10e'
down_revision: Union[str, None] = '1df688c3e6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('source_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'role', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_column('role', 'source_id')
    # ### end Alembic commands ###
