"""edit presentation_files

Revision ID: 339a3a1bec6b
Revises: 18b343b83512
Create Date: 2025-01-23 09:39:04.744807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339a3a1bec6b'
down_revision: Union[str, None] = '18b343b83512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('presentation_files', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('presentation_files', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
