"""Add task_status table

Revision ID: 3a439617a426
Revises: 84a90e56a975
Create Date: 2025-02-17 09:42:38.851191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a439617a426'
down_revision: Union[str, None] = '84a90e56a975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_user', 'login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('external_user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('external_user', 'login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
