"""add is_deleted

Revision ID: 4bdc2e0f633f
Revises: 339a3a1bec6b
Create Date: 2025-01-29 11:45:41.574791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bdc2e0f633f'
down_revision: Union[str, None] = '339a3a1bec6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentation_files', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presentation_files', 'is_deleted')
    # ### end Alembic commands ###
