"""Add login in external_user

Revision ID: 84a90e56a975
Revises: 8b260d9028f2
Create Date: 2025-02-14 10:04:18.105312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a90e56a975'
down_revision: Union[str, None] = '8b260d9028f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_user', sa.Column('login', sa.String(), nullable=True))
    op.add_column('external_user', sa.Column('password', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'external_user', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'external_user', type_='unique')
    op.drop_column('external_user', 'password')
    op.drop_column('external_user', 'login')
    # ### end Alembic commands ###
