"""edit logs

Revision ID: 8b260d9028f2
Revises: fad90dd1384b
Create Date: 2025-02-06 12:22:35.246078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b260d9028f2'
down_revision: Union[str, None] = 'fad90dd1384b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('traceback', sa.Text(), nullable=True))
    op.alter_column('logs', 'message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('logs', 'traceback')
    # ### end Alembic commands ###
