"""edit user

Revision ID: a684ebcf87f2
Revises: f797db06feb6
Create Date: 2025-01-21 10:21:07.605081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a684ebcf87f2'
down_revision: Union[str, None] = 'f797db06feb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_user', sa.Column('access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_user', 'access_token')
    # ### end Alembic commands ###
