"""edit is_deleted

Revision ID: f21bf9f0517e
Revises: 4bdc2e0f633f
Create Date: 2025-01-29 11:47:59.557477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f21bf9f0517e'
down_revision: Union[str, None] = '4bdc2e0f633f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Установить значение по умолчанию для всех NULL-записей
    op.execute("UPDATE files SET is_deleted = FALSE WHERE is_deleted IS NULL;")
    op.execute("UPDATE presentation_files SET is_deleted = FALSE WHERE is_deleted IS NULL;")

    # Теперь можно изменить столбец
    op.alter_column('files', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('presentation_files', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('presentation_files', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('files', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
