"""Add task_id to PresentationFile

Revision ID: f262eac11ece
Revises: 3a439617a426
Create Date: 2025-02-17 10:05:38.943972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f262eac11ece'
down_revision: Union[str, None] = '3a439617a426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_statuses',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILURE', name='task_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_task_statuses_task_id'), 'task_statuses', ['task_id'], unique=False)
    op.add_column('presentation_files', sa.Column('task_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'presentation_files', 'task_statuses', ['task_id'], ['task_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'presentation_files', type_='foreignkey')
    op.drop_column('presentation_files', 'task_id')
    op.drop_index(op.f('ix_task_statuses_task_id'), table_name='task_statuses')
    op.drop_table('task_statuses')
    # ### end Alembic commands ###
